package by.cyberpunkfandom.domain.exceptions

enum class ExceptionCodes {
    MISSING_PARAMETER,
    ADMIN_AUTH_FAILED,
    WORKER_NOT_FOUND,
    WORKER_MUST_HAVE_ROLE,
    WORKER_ROLE_NOT_ALLOWED,
    ORDER_NOT_FOUND,
    ORDER_IN_INCOMPATIBLE_STATUS,
    ORDER_MUST_HAVE_ITEMS,
    UNKNOWN,
}
